### ISSUE TITLE
Windows 11 22H2 2024-02 (windows11.0-kb5034765-x64_d82c9af459245e90b5bf897f15a72cf810819f31) 0kb?

### ISSUE THREAD

**Issue by xe0n11** [OSDeploy/OSDSUS#10]
Anyone else seeing the following file downloading and being 0kb?  windows11.0-kb5034765-x64_d82c9af459245e90b5bf897f15a72cf810819f31.msu

![image](https://github.com/OSDeploy/OSDSUS/assets/53819142/85fd1d2c-9bb6-466e-8f53-43fa268beef9)

![image](https://github.com/OSDeploy/OSDSUS/assets/53819142/cacf0ed5-15e8-437a-8fce-5797771f19eb)

https://www.catalog.update.microsoft.com/Search.aspx?q=kb5034765 shows the following for Windows 11 22H2\23H2 - windows11.0-kb5034765-x64_0b9338c4ace818aa52dbef7f674250aeb341f0f1.msu

![image](https://github.com/OSDeploy/OSDSUS/assets/53819142/6baf1d93-b4ea-440b-95e0-9f3d168a2292)

**Comment by OSDeploy** [comment]
I manually tested the URL before releasing the module update, and just opened the catalog and tested the link again and it's downloading.  It will be at least 12 hours before I can test using OSDBuilder
![image](https://github.com/OSDeploy/OSDSUS/assets/12970006/b26bd49d-7a72-4ff8-b228-b8f838018d45)

**Comment by OSDeploy** [comment]
FYI, OSDBuilder does not use OSDSUS.  It uses catalogs in the OSD Module.

**Comment by xe0n11** [comment]
Cheers David, will investigate further at my end. Might be a CDN thing, tested on a couple of different connections and get 404.

**Comment by xe0n11** [comment]
Can confirm the 0kb download on multiple instances of OSD, and different internet connections. 👍

**Comment by Rickard-l** [comment]
> FYI, OSDBuilder does not use OSDSUS. It uses catalogs in the OSD Module.

Can confirm this issue aswell. I understand the issue may be placed under the wrong project, but i'll contribute with my findings.





> Can confirm the 0kb download on multiple instances of OSD, and different internet connections. :)

When running the `Update-OSMedia -Download -Execute` on my build machine. I'm also seeing this 0 KB download:

![Untitled](https://github.com/OSDeploy/OSDSUS/assets/27015673/7ac62cbb-70b7-4896-ac7b-74982d76642f)

I tried to download the exact URL provided in: https://github.com/OSDeploy/OSDSUS/blob/48241ab81f442b98c87fd01560856f540c417813/Catalogs/Windows/Windows%2011%2022H2%20LCU.xml#L50

https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/a9f5de65-91c3-47e7-b987-0ba0468699b8/public/windows11.0-kb5034765-x64_d82c9af459245e90b5bf897f15a72cf810819f31.msu 


I cannot manage to download this file, i'm receiving 404 from multiple devices and ISPs.
![This catalog sf dl delivery mp microsoft com page can’t be found](https://github.com/OSDeploy/OSDSUS/assets/27015673/25f54ed7-ce3d-4c22-8823-8e7025d3632b)

Also when comparing the lastest LCU on Microsofts release notes and the CSV/JSON in the repo. I found the files was not the same:

[Microsoft download catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5034765): 

- https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/bde66034-3c41-4fca-992a-54d476045855/public/windows11.0-kb5034765-x64_0b9338c4ace818aa52dbef7f674250aeb341f0f1.msu


[OSDSUS/Catalogs/Windows/Windows 11 22H2 LCU.xml](https://github.com/OSDeploy/OSDSUS/blob/48241ab81f442b98c87fd01560856f540c417813/Catalogs/Windows/Windows%2011%2022H2%20LCU.xml#L50): 

- https://catalog.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/a9f5de65-91c3-47e7-b987-0ba0468699b8/public/windows11.0-kb5034765-x64_d82c9af459245e90b5bf897f15a72cf810819f31.msu

**Comment by xe0n11** [comment]
FYI - Noticed the OSD module was updated, however the 0kb file download is still present.
