### ISSUE TITLE
Not getting SSU for Windows 10 20H2

### ISSUE THREAD

**Issue by tobbelobbe02** [OSDeploy/OSDSUS#2]
Hi
i'm not getting the SSU for Windows 10 20H2, i'm using WIMWitch.

**Comment by OSDeploy** [comment]
This has been resolved in the latest release.  Thanks for letting me know!

**Comment by tobbelobbe02** [comment]
Hi
I’m using the latest version…

Regards
Tobias

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
