### ISSUE TITLE
No updates for Win 10 22H2 2023-08

### ISSUE THREAD

**Issue by Dron2328** [OSDeploy/OSDSUS#7]

**Comment by dhekimian** [comment]
**Windows 10 22H2.csv**, **Windows 10 22H2.json**, **Windows 10 22H2.xml** were updated to point to the latest KB's but often times they are shared with multiple Windows 10 releases so the **UPDATES.md** might not specifically say **Windows 10 22H2**.

For example, if you look at [UPDATES.md](https://raw.githubusercontent.com/OSDeploy/OSDSUS/master/UPDATES.md) you'll see:
`8/8/2023 5:00:07 PM    5029244  2023-08 Cumulative Update for Windows 10 Version 21H2 for x64-based Systems (KB5029244)`

Looking up the [KB5029244](https://support.microsoft.com/en-gb/topic/august-8-2023-kb5029244-os-builds-19044-3324-and-19045-3324-46087102-62c2-4911-9896-da3c6f4d8b5c), you'll see that it points to **Windows 10, version 22H2** even though the description says in UPDATES.md says **Windows 10 Version 21H2**

**Comment by burnacid** [comment]
I don't see any 2023-08 updates. Any clues why this happens?

<img width="758" alt="image" src="https://github.com/OSDeploy/OSDSUS/assets/852616/7a1f586f-a079-45ba-b598-a0dea1c16fc8">

**Comment by burnacid** [comment]
Never mind, If I manually download the catalogs from git and drop them into my powershell module folder I can get the definitions. Though this normally should update automatically right?

**Comment by OSDeploy** [comment]
What are you using OSDSUS for?  WSUSXML is part of the OSD Module and is updated.  I think only WinWitch uses OSDSUS

**Comment by burnacid** [comment]
I did switch my code to use OSDBuilder. Did use WinWitch before indeed.

**Comment by OSDeploy** [comment]
Still working on this week's update.  Should be up tonight.

**Comment by xe0n11** [comment]
Noticed the catalogs were updated to 23.9.18.1, except Windows 11.

Have you given any thought about documenting the process of creating the catalog files so others can assist?

**Comment by OSDeploy** [comment]
Due to UUP, Windows 11 is not automated, but has to be manually added (and tested). I should have the updated OSDSUS Module published to PSGallery later tonight when I get the Windows 11 downloads created.

I can document the process, but due to time constraints, its going to be a ways out (and will require a WSUS server to create).  Unfortunately, with the way UUP updates are being released (and Feature Updates are going to be UUP) there may not be a path forward for new releases

**Comment by xe0n11** [comment]
No sweat, cheers, understand.

Look forward to the documentation, I rely on the module, so happy to assist if it means the module will continue to work as expected (I have the infra to test etc).

**Comment by xe0n11** [comment]
Thanks mate 🍻👍
