### ISSUE TITLE
2024-01 CU for Windows 11 22h2 missing from catalog

### ISSUE THREAD

**Issue by w0** [OSDeploy/OSDSUS#9]
In the release [24.1.11.1](https://github.com/OSDeploy/OSDSUS/commit/dfcfc25aeaba530d517cea20083d77d1e536df38) the catalogs for Windows 11 22H2 is missing the CU for 2024-01

**Comment by OSDeploy** [comment]
The newer LCU's are manually generated and take some time to create and test.  I decided to push the last release without this update.  Are you pointing this out based on need?  If so, I can update the catalogs tonight with this update.

**Comment by w0** [comment]
No immediate need for this update. I was just working through the monthly maintenance on my windows images and noticed this. I was not aware it was a manual process.

**Comment by Jim-Webb** [comment]
I was attempting to update an old media import and since the January 2024 update isn't available, no CU is installed. 

Why doesn't OSDBuilder install the previous month's update, or whatever the latest available is?

**Comment by Simsi1986** [comment]
@Jim-Webb  Unfortunately because all previous CUs are replaced by the latest one released

@OSDeploy I know your current job is binding you more than in the past, which makes it difficult to keep the repositories current. Is there any way to reduce the effort for manual work on Win11 updates lower to make it possible that CUs are included regulary? I wonder whether the msu files can be just replaced without add. testing or is there more to consider than just replace the file?

**Comment by OSDeploy** [comment]
I can have them posted tomorrow if that works.  My new job at HP wasn't focused on OSD, so yes, it's been a shift ... but that changed a few days ago.  I'll share more soon, but for now I can get everything up to date tomorrow.

**Comment by OSDeploy** [comment]
It's interesting that the updates are identical for 22H2 and 23H2.  You can tell as the download has a string in the file name which is actually the SHA1 hash 
![image](https://github.com/OSDeploy/OSDSUS/assets/12970006/87854a17-015f-4545-8758-ebf88f61ac83)

**Comment by OSDeploy** [comment]
Resolved in OSD 24.2.4.1
https://www.powershellgallery.com/packages/OSD/24.2.4.1

**Comment by Simsi1986** [comment]
> I can have them posted tomorrow if that works. My new job at HP wasn't focused on OSD, so yes, it's been a shift ... but that changed a few days ago. I'll share more soon, but for now I can get everything up to date tomorrow.
That are great news, I cross fingers that there is some opportunities not only to be able to keep OSDeply maintained more frequently but also some relief beeing able to achieve work life balance :)

> Resolved in OSD 24.2.4.1 https://www.powershellgallery.com/packages/OSD/24.2.4.1
Happy to notice, much appreciated!
